# Generated by Django 3.1.2 on 2020-10-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_auto_20201012_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='media/images/'),
        ),
    ]
